### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by asztalosors** [fusion-flap/flap_field_lines#6]
While running initiating the FieldLineHandler class in the edvis conda environment (which runs python3.7) the following error was encountered: 

 from flap_field_lines.field_line_handler import FieldLineHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asztalos/flap_field_lines/field_line_handler.py", line 8, in <module>
    from typing import get_args
ImportError: cannot import name 'get_args' from 'typing' (/home/asztalos/anaconda3/envs/edvis/lib/python3.7/typing.py)

This does not occur when the FieldLineHandler is initiated with python 3.8, more so supported by the fact the (if I read it correctly) **get_args** function is included in python3.8. I looked through the source code of "typing.py" in the path specified by the conda env and can confirm, it is void of any such routine.

What would be the solution? How resilient would be edvis for a python 3.8 upgrade? Or would it be not much of a hassle to use python 3.7 language for the tasks performed by get_args.?

**Comment by asztalosors** [comment]
Upon closer examination of the typing.get_args function seems to be unused and looks like code leftover.

**Comment by lordofbejgli** [comment]
You're right, thanks for catching it. Removed it, tests are running green, change pushed to development branch.
