### ISSUE TITLE
Requirements.txt missing

### ISSUE THREAD

**Issue by asztalosors** [fusion-flap/flap_field_lines#8]
As flap_field_lines is envisioned to work with EDVIS, most likely within a conda env generated by the latter, it is necessary to have a clear picture of flap_field_lines dependencies. 

For starters edvis does not use scipy, thus the conda environment does not support flap_field_lines. It would make it easier to install and build the env if requirements would exist.

**Comment by lordofbejgli** [comment]
Added requirements.txt to development branch.
